@startuml
title SmartHouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the web or mobile application")
Container_Boundary(JavaApp, "Java application") {
    System(Мониторинг, "мониторинг температуры", "")
    System(Управление, "управление отоплением", "")
}
System_Ext(датчик, "Датчики температуры", "АПИ для получения температуры")
System_Ext(реле, "реле управления отоплением", "апи для включения/отключения отопления")

Rel(user, Мониторинг, "просмотр текущей температуры")
Rel(user, Управление, "управление отоплением")
Rel(Мониторинг,Управление,"Manages the system")
Rel(Мониторинг,датчик,"запрос температуры ")
Rel(Управление,реле,"управляющие команды")

@enduml